name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Test By Pytest
        run:
          pytest pyvalidation

      - name: Python Unit Test
        run:
          python -m unittest

