name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
      max-parallel: 1

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Test By Pylint
        run: |
          pylint pyvalidation

      - name: Python Unit Test
        run: |
          python -m unittest

